# Generated by Django 5.2 on 2025-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_remove_usuarioconperfil_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionpaqueteperfil',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Asignación de Paquete a Perfil de Usuario', 'verbose_name_plural': 'Asignaciones Paquetes Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='usuarioperfil',
            options={'ordering': ['usuario__username', 'perfil__nombre'], 'verbose_name': 'Asignación de Usuario a Perfil', 'verbose_name_plural': 'Usuarios Perfiles'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('1', 'Capturista'), ('2', 'Otro')], default=1, max_length=1),
        ),
    ]
