# Generated by Django 5.2 on 2025-07-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_alter_usuarioperfil_perfil_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionpaqueteperfil',
            unique_together={('paquete', 'usuario_perfil')},
        ),
        migrations.AddField(
            model_name='asignacionpaqueteperfil',
            name='usuario_perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_paquetes', to='gestion.usuarioperfil'),
        ),
        migrations.RemoveField(
            model_name='asignacionpaqueteperfil',
            name='perfil',
        ),
    ]
