# Generated by Django 5.2 on 2025-07-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_alter_asignacionpaqueteperfil_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionpaqueteperfil',
            unique_together=set(),
        ),
    ]
