# Generated by Django 5.2 on 2025-07-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0041_alter_asignacionpaqueteperfil_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='gestion.perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionpaqueteperfil',
            unique_together={('paquete', 'usuario_perfil')},
        ),
    ]
