# Generated by Django 5.2 on 2025-07-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_alter_usuarioperfil_perfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionpaqueteperfil',
            old_name='usuario_perfil',
            new_name='perfil',
        ),
        migrations.AlterUniqueTogether(
            name='asignacionpaqueteperfil',
            unique_together={('paquete', 'perfil')},
        ),
    ]
