# Generated by Django 5.2 on 2025-04-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('clave', models.CharField(max_length=50)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('rgb_color_identificacion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('ambito', models.CharField(blank=True, max_length=2, null=True)),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.estado')),
                ('id_municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Juzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('clave_interna', models.CharField(max_length=50)),
                ('archivo_regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.archivoregional')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='NombreJuzgadoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo_cambio', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=False)),
                ('juzgado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_historicos', to='administracion.juzgado')),
            ],
            options={
                'verbose_name_plural': 'Histórico de nombres de juzgados',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
