# Generated by Django 5.2 on 2025-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juzgado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FAMILIAR'), (2, 'MERCANTIL'), (3, 'CIVIL'), (4, 'PENAL'), (5, 'LABORAL'), (6, 'MIXTO'), (7, 'CONCILIACION'), (8, 'OFICIALIA DE PARTES'), (9, 'DE PAZ '), (13, 'FEDERAL'), (14, 'CONSIGNACIONES Y PAGOS')], default=1),
        ),
    ]
