# Generated by Django 5.2 on 2025-04-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_juzgado_created_at_juzgado_direccion_juzgado_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoregional',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archivoregional',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivoregional',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archivoregional',
            name='rgb_color_identificacion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
