# Generated by Django 5.2 on 2025-05-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_archivoregional_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoregional',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1),
        ),
    ]
