# Generated by Django 5.2 on 2025-05-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_distritojudicial_instancia_materia_tipojuicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nombrejuzgadohistorico',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Histórico nombres juzgado'},
        ),
        migrations.AlterModelOptions(
            name='tipojuicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo juicio', 'verbose_name_plural': 'Tipo juicio'},
        ),
        migrations.AddField(
            model_name='distritojudicial',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1),
        ),
        migrations.AddField(
            model_name='instancia',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1),
        ),
        migrations.AddField(
            model_name='materia',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1),
        ),
        migrations.AddField(
            model_name='tipojuicio',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1),
        ),
    ]
