# Generated by Django 5.2 on 2025-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_nombrejuzgadohistorico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoJuzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('estatus', models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo juzgado',
                'verbose_name_plural': 'Tipo juzgado',
                'ordering': ['nombre'],
            },
        ),
    ]
