# Generated by Django 5.2 on 2025-05-06 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_tipojuzgado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juzgado',
            name='tipo',
        ),
        migrations.AddField(
            model_name='juzgado',
            name='tipo_juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.tipojuzgado'),
        ),
    ]
