# Generated by Django 5.2 on 2025-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_remove_juzgado_tipo_juzgado_tipo_juzgado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juzgado',
            name='clave_interna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
