# Generated by Django 5.2 on 2025-05-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_juzgado_clave_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='juzgado',
            name='locacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
