# Generated by Django 5.2 on 2025-05-09 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_juzgado_locacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoregional',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivo_actualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivoregional',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivo_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivoregional',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='archivoregional',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='distritojudicial',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos_actualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distritojudicial',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instancia',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instancia',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_actualizada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materia',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_creada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipojuicio',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_juicio_actualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipojuicio',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_jucio_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipojuzgado',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_juzgado_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipojuzgado',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_juzgado_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distritojudicial',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='distritojudicial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipojuicio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipojuicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipojuzgado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipojuzgado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
