# Generated by Django 5.2 on 2025-05-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_archivoregional_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoregional',
            name='locacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivoregional',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.municipio'),
        ),
    ]
