# Generated by Django 5.2 on 2025-05-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_archivoregional_locacion_archivoregional_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juzgado',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
