# Generated by Django 5.2 on 2025-05-21 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_remove_archivoregional_actualizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoregional',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivo_actualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivoregional',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivo_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracion_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('archivo_regional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_regional', to='administracion.archivoregional')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracion_creadas', to=settings.AUTH_USER_MODEL)),
                ('juzgado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juzgado', to='administracion.juzgado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
