# Generated by Django 5.2 on 2025-05-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_archivoregional_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Configuraciones USER'},
        ),
        migrations.AddField(
            model_name='juzgado',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materia_juzgado', to='administracion.materia'),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='tipo_juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_juzgado_materia', to='administracion.tipojuzgado'),
        ),
    ]
