# Generated by Django 5.2 on 2025-05-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_alter_userconfig_options_juzgado_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distritojudicial',
            name='archivo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.archivoregional'),
        ),
    ]
