# Generated by Django 5.2 on 2025-05-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_distritojudicial_archivo_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='juzgado',
            name='distrito_judicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.distritojudicial', verbose_name='Distrito Judicial o Región'),
        ),
    ]
