# Generated by Django 5.2 on 2025-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_alter_juzgado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juzgado',
            name='nombre',
            field=models.CharField(max_length=550),
        ),
    ]
