# Generated by Django 5.2 on 2025-05-30 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_alter_juzgado_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('estatus', models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_judicial_actualizado', to=settings.AUTH_USER_MODEL)),
                ('archivo_regional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.archivoregional')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_judicial_creado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Región judicial',
                'verbose_name_plural': 'Regiones judijciales',
                'ordering': ['nombre'],
            },
        ),
    ]
