# Generated by Django 5.2 on 2025-05-31 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0021_regionjudicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juzgado',
            name='region_judicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.regionjudicial', verbose_name='Región Judicial'),
        ),
    ]
