# Generated by Django 5.2 on 2025-06-03 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_juzgado_region_judicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='juzgado',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juzgado_actualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juzgado_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganoJurisdiccional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=550)),
                ('nombre_corto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('clave_interna', models.CharField(blank=True, max_length=50, null=True)),
                ('locacion', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('estatus', models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organo_jurisdiccional_actualizado', to=settings.AUTH_USER_MODEL)),
                ('archivo_regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.archivoregional')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organo_jurisdiccional_creado', to=settings.AUTH_USER_MODEL)),
                ('distrito_judicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.distritojudicial', verbose_name='Distrito Judicial o Región')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materia_organo_jurisdiccional', to='administracion.materia')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.municipio')),
                ('region_judicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.regionjudicial', verbose_name='Región Judicial')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_organo_jurisdiccional', to='administracion.tipojuzgado')),
            ],
        ),
    ]
