# Generated by Django 5.2 on 2025-06-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_alter_juzgado_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organojurisdiccional',
            name='tipo_organo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'JUZGADO'), (2, 'TRIBUNAL')], default=1),
        ),
    ]
