# Generated by Django 5.2 on 2025-06-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_organojurisdiccional_tipo_organo'),
    ]

    operations = [
        migrations.AddField(
            model_name='distritojudicial',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.municipio'),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='tipo_organo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Juzgado'), (2, 'Tribunal')], default=1),
        ),
    ]
