# Generated by Django 5.2 on 2025-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0025_distritojudicial_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distritojudicial',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='distritojudicial',
            name='locacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
