# Generated by Django 5.2 on 2025-06-04 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0026_distritojudicial_direccion_distritojudicial_locacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organo_jurisdiccional', to='administracion.organojurisdiccional'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='archivo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_regional', to='administracion.archivoregional'),
        ),
    ]
