# Generated by Django 5.2 on 2025-06-05 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_userconfig_organo_jurisdiccional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distritojudicial',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materia_distrito_judicial', to='administracion.materia'),
        ),
    ]
