# Generated by Django 5.2 on 2025-06-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0028_distritojudicial_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionjudicial',
            name='archivo_regional',
        ),
        migrations.AddField(
            model_name='regionjudicial',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materia_region_judicial', to='administracion.materia'),
        ),
    ]
