# Generated by Django 5.2 on 2025-06-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0029_remove_regionjudicial_archivo_regional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juzgado',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organojurisdiccional',
            name='created_at',
        ),
        migrations.AddField(
            model_name='organojurisdiccional',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancia_organo_jurisdiccional', to='administracion.instancia'),
        ),
    ]
