# Generated by Django 5.2 on 2025-06-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0030_remove_juzgado_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='es_administrador_general',
            field=models.BooleanField(default=False, verbose_name='Administrador general'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='es_administrador_regional',
            field=models.BooleanField(default=False, verbose_name='Administrador regional del archivo'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='es_capturista_regional',
            field=models.BooleanField(default=False, verbose_name='Capturista del archivo regional'),
        ),
    ]
