# Generated by Django 5.2 on 2025-06-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0032_logcambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcambio',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
