# Generated by Django 5.2 on 2025-06-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0033_logcambio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcambio',
            name='relacionado_con_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logcambio',
            name='relacionado_con_modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
