# Generated by Django 5.2 on 2025-06-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0034_logcambio_relacionado_con_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcambio',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('actualizado', 'Actualizado'), ('eliminado', 'Eliminado')], max_length=20),
        ),
    ]
