# Generated by Django 5.2 on 2025-06-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0035_alter_logcambio_accion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logcambio',
            old_name='fecha',
            new_name='fecha_accion',
        ),
    ]
