# Generated by Django 5.2 on 2025-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0036_rename_fecha_logcambio_fecha_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcambio',
            name='app_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
