# Generated by Django 5.2 on 2025-06-30 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0037_logcambio_app_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivoregional',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_regionales_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivoregional',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_regionales_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distritojudicial',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distritojudicial',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distritojudicial',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='administracion.materia'),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juzgados_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juzgados_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juzgados', to='administracion.materia'),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='tipo_juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juzgados', to='administracion.tipojuzgado'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materia',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organos_jurisdiccionales_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='archivo_regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organos_jurisdiccionales', to='administracion.archivoregional'),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organos_jurisdiccionales_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='distrito_judicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organos_jurisdiccionales', to='administracion.distritojudicial', verbose_name='Distrito Judicial o Región'),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organos_jurisdiccionales', to='administracion.instancia'),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organos_jurisdiccionales', to='administracion.materia'),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organos_jurisdiccionales', to='administracion.municipio'),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='region_judicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organos_jurisdiccionales', to='administracion.regionjudicial', verbose_name='Región Judicial'),
        ),
        migrations.AlterField(
            model_name='organojurisdiccional',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organos_jurisdiccionales', to='administracion.tipojuzgado'),
        ),
        migrations.AlterField(
            model_name='regionjudicial',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regiones_judiciales_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regionjudicial',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regiones_judiciales_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regionjudicial',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regiones_judiciales', to='administracion.materia'),
        ),
        migrations.AlterField(
            model_name='tipojuicio',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_juicios_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipojuicio',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_jucios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipojuicio',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_juicios_materia', to='administracion.materia'),
        ),
        migrations.AlterField(
            model_name='tipojuzgado',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_juzgado_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipojuzgado',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_juzgado_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='archivo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_usuario', to='administracion.archivoregional'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='juzgado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_usuario', to='administracion.juzgado'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_usuario', to='administracion.organojurisdiccional'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL),
        ),
    ]
