# Generated by Django 5.2 on 2025-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0038_userconfig_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='es_usuario_consultor',
            field=models.BooleanField(default=False, verbose_name='Consultor'),
        ),
    ]
