# Generated by Django 5.2 on 2025-07-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0039_userconfig_es_usuario_consultor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='es_usuario_consultor',
            new_name='es_usuario_consulta',
        ),
    ]
