# Generated by Django 5.2 on 2025-08-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0040_rename_es_usuario_consultor_userconfig_es_usuario_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcambio',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('actualizado', 'Actualizado'), ('eliminado', 'Eliminado'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='es_usuario_consulta',
            field=models.BooleanField(default=False, verbose_name='Usuario de consulta'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_usuario', to='administracion.juzgado'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='organo_jurisdiccional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_usuario', to='administracion.organojurisdiccional'),
        ),
    ]
