# Generated by Django 5.2 on 2025-07-02 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0038_userconfig_creado_por_and_more'),
        ('gestion', '0037_alter_acumulado_actualizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioconperfil',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='usuarioconperfil',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='usuarioconperfil',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuarioconperfil',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nombre'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='archivo_regional',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='organo_jurisdiccional',
        ),
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('1', 'Capturista'), ('2', 'Otro')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='perfil',
            name='visibilidad_paquetes',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HistorialAsignacionPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('A', 'Asignación'), ('R', 'Reasignación'), ('D', 'Desasignación'), ('C', 'Cambio de estado')], default='A', max_length=1)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignaciones_actualizados', to=settings.AUTH_USER_MODEL)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='gestion.paquete')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignaciones', to='gestion.perfil')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Asignación',
                'verbose_name_plural': 'Historial de Asignaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_perfiles_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('archivo_regional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_por_archivo', to='administracion.archivoregional')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_perfiles_creadas', to=settings.AUTH_USER_MODEL)),
                ('organo_jurisdiccional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_por_organo', to='administracion.organojurisdiccional')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='gestion.perfil')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Usuario a Perfil',
                'verbose_name_plural': 'Usuarios Perfiles',
                'ordering': ['usuario__username', 'perfil__nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionPaquetePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'En revisión'), (3, 'Completado')], default=1)),
                ('tipo_asignacion', models.CharField(choices=[('A', 'Automática'), ('M', 'Manual')], default='M', max_length=1)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.PositiveSmallIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_asignados_actualizados', to=settings.AUTH_USER_MODEL)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_asignados_a_perfiles', to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_perfiles', to='gestion.paquete')),
                ('usuario_perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_paquetes', to='gestion.usuarioperfil')),
            ],
            options={
                'verbose_name': 'Asignación de Paquete a Perfil de Usuario',
                'verbose_name_plural': 'Asignaciones Paquetes Perfiles',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='AsignacionPaquetePorPerfil',
        ),
        migrations.DeleteModel(
            name='UsuarioConPerfil',
        ),
        migrations.AddIndex(
            model_name='historialasignacionpaquete',
            index=models.Index(fields=['paquete'], name='gestion_his_paquete_3e42b0_idx'),
        ),
        migrations.AddIndex(
            model_name='historialasignacionpaquete',
            index=models.Index(fields=['perfil'], name='gestion_his_perfil__500e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='historialasignacionpaquete',
            index=models.Index(fields=['usuario_asignado'], name='gestion_his_usuario_dcd681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioperfil',
            unique_together={('usuario', 'perfil')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacionpaqueteperfil',
            unique_together={('paquete', 'usuario_perfil')},
        ),
    ]
