# Generated by Django 5.2 on 2025-07-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_alter_asignacionpaqueteperfil_options_and_more'),
        ('gestion', '0039_alter_usuarioperfil_perfil_and_more'),
    ]

    operations = [
    ]
