# Generated by Django 5.2 on 2025-07-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_merge_20250702_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='gestion.perfil'),
        ),
    ]
