# Generated by Django 5.2 on 2025-05-08 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0010_juzgado_locacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('nota', models.TextField()),
                ('estatus', models.PositiveSmallIntegerField(choices=[(1, 'Creación'), (2, 'Captura'), (3, 'Cierre')], default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('juzgado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.juzgado')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tomo', models.BooleanField(default=False)),
                ('numero_tomo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de tomo')),
                ('actor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Actor/Ofendido')),
                ('demandado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Demandado/Inculpado')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_sentencia', models.DateField(blank=True, null=True)),
                ('fecha_archivo', models.DateField(blank=True, null=True)),
                ('juez', models.CharField(blank=True, max_length=200, null=True)),
                ('secretario', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiario', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_convenio', models.DateField(blank=True, null=True)),
                ('original', models.BooleanField(default=False)),
                ('duplicado', models.BooleanField(default=False)),
                ('cuadernillo', models.BooleanField(default=False, verbose_name='Cuardenillo')),
                ('acumulado', models.BooleanField(default=False)),
                ('numero_acumulado', models.CharField(blank=True, max_length=50, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('fecha_concluido', models.DateField(blank=True, null=True)),
                ('distrito_judicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.distritojudicial', verbose_name='Distrito Judicial o Región')),
                ('instancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.instancia', verbose_name='Instancia a la que pertenece')),
                ('juzgado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.juzgado')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.materia', verbose_name='Materia del expediente')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.municipio')),
                ('tipo_juicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.tipojuicio', verbose_name='Tipo de juicio')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.paquete')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['numero'], name='gestion_exp_numero_7265e7_idx'), models.Index(fields=['juzgado'], name='gestion_exp_juzgado_a09dba_idx'), models.Index(fields=['fecha_inicio'], name='gestion_exp_fecha_i_068790_idx')],
            },
        ),
    ]
