# Generated by Django 5.2 on 2025-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
