# Generated by Django 5.2 on 2025-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_paquete_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='numero_paquete',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
