# Generated by Django 5.2 on 2025-05-08 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_juzgado_locacion'),
        ('gestion', '0003_paquete_numero_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='archivo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.archivoregional'),
        ),
    ]
