# Generated by Django 5.2 on 2025-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_paquete_archivo_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
