# Generated by Django 5.2 on 2025-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_expediente_actualizado_por_expediente_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='expediente_toca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Expediente/TOCA'),
        ),
    ]
