# Generated by Django 5.2 on 2025-05-14 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_archivoregional_actualizado_por_and_more'),
        ('gestion', '0007_expediente_expediente_toca'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='juicio_delito',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Juicio/Delito'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.instancia', verbose_name='Instancia'),
        ),
    ]
