# Generated by Django 5.2 on 2025-05-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_expediente_juicio_delito_alter_expediente_instancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_acumulado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número acumulado'),
        ),
    ]
