# Generated by Django 5.2 on 2025-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_expediente_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nueva creación'), (2, 'Captura'), (3, 'Cierre')], default=1),
        ),
    ]
