# Generated by Django 5.2 on 2025-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_paquete_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='clave_expediente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='letra',
            field=models.CharField(blank=True, help_text='Letra del expediente, por ejemplo: A, B, C', max_length=1, null=True),
        ),
    ]
