# Generated by Django 5.2 on 2025-05-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_expediente_clave_expediente_expediente_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='tipo_expediente',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Principal'), (2, 'Extensión')], default=1),
        ),
    ]
