# Generated by Django 5.2 on 2025-06-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_expediente_tipo_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='clave_paquete',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='letra',
            field=models.CharField(blank=True, help_text='Letra del paquete, por ejemplo: A, B, C', max_length=1, null=True),
        ),
    ]
