# Generated by Django 5.2 on 2025-06-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_paquete_clave_paquete_paquete_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='tipo_paquete',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Principal'), (2, 'Extensión')], default=1),
        ),
    ]
