# Generated by Django 5.2 on 2025-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_paquete_tipo_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
