# Generated by Django 5.2 on 2025-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_expediente_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='cuadernillo',
            field=models.BooleanField(default=False, verbose_name='Cuadernillo'),
        ),
    ]
