# Generated by Django 5.2 on 2025-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_expediente_cuadernillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_ejecutoria',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='rango_folio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rango de folios'),
        ),
    ]
