# Generated by Django 5.2 on 2025-06-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_userconfig_organo_jurisdiccional_and_more'),
        ('gestion', '0017_expediente_fecha_ejecutoria_expediente_rango_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='archivo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expediente_archivo_regional', to='administracion.archivoregional'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expediente_organo_jurisdiccional', to='administracion.organojurisdiccional'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquete_organo_jurisdiccional', to='administracion.organojurisdiccional'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='archivo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquete_archivo_regional', to='administracion.archivoregional'),
        ),
    ]
