# Generated by Django 5.2 on 2025-06-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_userconfig_organo_jurisdiccional_and_more'),
        ('gestion', '0018_expediente_archivo_regional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.juzgado'),
        ),
    ]
