# Generated by Django 5.2 on 2025-06-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_paquete_juzgado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='paquete_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.paquete'),
        ),
    ]
