# Generated by Django 5.2 on 2025-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_paquete_paquete_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
