# Generated by Django 5.2 on 2025-06-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_alter_expediente_descripcion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expediente',
            name='gestion_exp_juzgado_a09dba_idx',
        ),
        migrations.AddField(
            model_name='expediente',
            name='estatus_expediente',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nueva creación'), (2, 'Captura'), (3, 'Cierre')], default=1),
        ),
    ]
