# Generated by Django 5.2 on 2025-06-09 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0029_remove_regionjudicial_archivo_regional_and_more'),
        ('gestion', '0022_remove_expediente_gestion_exp_juzgado_a09dba_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acumulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=100)),
                ('rango_inicial', models.CharField(blank=True, max_length=200, null=True)),
                ('rango_final', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acumulado_actualizado', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acumulado_creado', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acumulados', to='gestion.expediente')),
                ('organo_jurisdiccional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acumulado_organo_jurisdiccional', to='administracion.organojurisdiccional')),
            ],
        ),
        migrations.CreateModel(
            name='Avocamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=100)),
                ('rango_inicial', models.CharField(blank=True, max_length=200, null=True)),
                ('rango_final', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avocamiento_actualizado', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avocamiento_creado', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avocamientos', to='gestion.expediente')),
                ('organo_jurisdiccional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avocamiento_organo_jurisdiccional', to='administracion.organojurisdiccional')),
            ],
        ),
        migrations.CreateModel(
            name='Cuadernillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('rango_inicial', models.CharField(blank=True, max_length=200, null=True)),
                ('rango_final', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadernillo_actualizado', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadernillo_creado', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadernillos', to='gestion.expediente')),
                ('organo_jurisdiccional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuadernillo_organo_jurisdiccional', to='administracion.organojurisdiccional')),
            ],
        ),
    ]
