# Generated by Django 5.2 on 2025-06-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_acumulado_avocamiento_cuadernillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='numero_paquete_letra',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
