# Generated by Django 5.2 on 2025-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_paquete_numero_paquete_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='avocamiento',
            field=models.BooleanField(default=True, verbose_name='Avocamiento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='acumulado',
            field=models.BooleanField(default=True, verbose_name='Acumulado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cuadernillo',
            field=models.BooleanField(default=True, verbose_name='Cuadernillo'),
        ),
    ]
