# Generated by Django 5.2 on 2025-06-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_expediente_avocamiento_alter_expediente_acumulado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='expediente_toca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tomo',
            field=models.BooleanField(default=True),
        ),
    ]
