# Generated by Django 5.2 on 2025-06-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_alter_expediente_expediente_toca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='actor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='demandado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Demandado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='juicio_delito',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Juicio'),
        ),
    ]
