# Generated by Django 5.2 on 2025-06-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_alter_expediente_actor_alter_expediente_demandado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Captura'), (2, 'Cerrado')], default=1),
        ),
    ]
