# Generated by Django 5.2 on 2025-06-13 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_alter_paquete_estatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuadernillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('estatus', models.PositiveSmallIntegerField(choices=[(0, 'No activo'), (1, 'Activo')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_cuadernillo_actualizado', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_cuadernillo_creado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de cuadernillo',
                'verbose_name_plural': 'Tipos de cuadernillo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cuadernillo',
            name='tipo_cuadernillo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuadernillo_tipo', to='gestion.tipocuadernillo'),
        ),
    ]
