# Generated by Django 5.2 on 2025-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_tipocuadernillo_cuadernillo_tipo_cuadernillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadernillo',
            name='tipo',
            field=models.CharField(max_length=300),
        ),
    ]
