# Generated by Django 5.2 on 2025-06-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_alter_cuadernillo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estatus_expediente',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Captura'), (2, 'En proceso'), (3, 'Cierre')], default=1),
        ),
    ]
