# Generated by Django 5.2 on 2025-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_alter_expediente_estatus_expediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='rango_folio',
        ),
        migrations.AddField(
            model_name='expediente',
            name='rango_folio_final',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rango de folio final'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='rango_folio_inicial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rango de folio inicial'),
        ),
    ]
