# Generated by Django 5.2 on 2025-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_remove_expediente_rango_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='medida_centimetros',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medida en centimetros'),
        ),
    ]
