# Generated by Django 5.2 on 2025-06-19 15:43

import apps_sicpej.gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_expediente_medida_centimetros'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='documento_prestamo',
            field=models.FileField(blank=True, null=True, upload_to=apps_sicpej.gestion.models.archivo_upload_path),
        ),
    ]
