# Generated by Django 5.2 on 2025-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_expediente_documento_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='ultimo',
            field=models.BooleanField(default=False),
        ),
    ]
