# Generated by Django 5.2 on 2025-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_paquete_ultimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='topografia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
