# Generated by Django 5.2 on 2025-06-30 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0038_userconfig_creado_por_and_more'),
        ('gestion', '0036_paquete_topografia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumulado',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acumulados_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acumulado',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acumulados_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acumulado',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acumulados', to='administracion.organojurisdiccional'),
        ),
        migrations.AlterField(
            model_name='avocamiento',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avocamientos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avocamiento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avocamientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avocamiento',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avocamientos', to='administracion.organojurisdiccional'),
        ),
        migrations.AlterField(
            model_name='cuadernillo',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadernillos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuadernillo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadernillos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuadernillo',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuadernillos', to='administracion.organojurisdiccional'),
        ),
        migrations.AlterField(
            model_name='cuadernillo',
            name='tipo_cuadernillo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuadernillos', to='gestion.tipocuadernillo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='archivo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='administracion.archivoregional'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='administracion.organojurisdiccional'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='archivo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='administracion.archivoregional'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Creado'), (2, 'Asignado'), (3, 'Cerrado')], default=1),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='organo_jurisdiccional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='administracion.organojurisdiccional'),
        ),
        migrations.AlterField(
            model_name='tipocuadernillo',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_cuadernillos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipocuadernillo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_cuadernillos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
