# Generated by Django 5.2 on 2025-07-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_perfil_usuarioperfil_historialasignacionpaquete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialasignacionpaquete',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='historialasignacionpaquete',
            name='asignado_por',
        ),
        migrations.RemoveField(
            model_name='historialasignacionpaquete',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='historialasignacionpaquete',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='historialasignacionpaquete',
            name='usuario_asignado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perfil',
        ),
        migrations.AlterUniqueTogether(
            name='usuarioperfil',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='archivo_regional',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='organo_jurisdiccional',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='AsignacionPaquetePerfil',
        ),
        migrations.DeleteModel(
            name='HistorialAsignacionPaquete',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='UsuarioPerfil',
        ),
    ]
