# Generated by Django 5.2 on 2025-07-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_perfil_usuarioperfil_historialasignacionpaquete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='clasificacion_paquete',
            field=models.CharField(choices=[('N', 'TRAMITE'), ('C', 'CONCLUIDO')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sin asignar'), (2, 'Asignado'), (3, 'Terminado')], default=1),
        ),
    ]
