# Generated by Django 5.2 on 2025-07-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_alter_paquete_clasificacion_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='clasificacion_paquete',
            field=models.CharField(choices=[('N', 'TRAMITE'), ('C', 'CONCLUIDO')], default='N', max_length=1),
        ),
    ]
