# Generated by Django 5.2 on 2025-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0043_alter_paquete_clasificacion_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='fecha_concluido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
