# Generated by Django 5.2 on 2025-08-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0044_paquete_fecha_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='ultimo',
            field=models.BooleanField(default=True),
        ),
    ]
