# Generated by Django 5.2 on 2025-09-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0045_alter_paquete_ultimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraInstancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_instancia', models.CharField(choices=[('1', 'Expediente'), ('2', 'Paquete')], default=0, max_length=2)),
                ('instancia_id', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('actualizado', 'Actualizado'), ('eliminado', 'Eliminado'), ('asignado_a', 'Asignado a')], max_length=20)),
                ('valores_anteriores', models.TextField(blank=True, null=True)),
                ('valores_nuevos', models.TextField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario_accion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_accion_bitacora', to=settings.AUTH_USER_MODEL)),
                ('usuario_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_asignado_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
