# Generated by Django 5.2 on 2025-09-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0046_bitacorainstancias'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_prestamo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='numero_oficio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='oficio_atencion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
