# Generated by Django 5.2 on 2025-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0047_expediente_fecha_prestamo_expediente_numero_oficio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpaqueteperfil',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
